### ISSUE TITLE
Python development headers required when installing from source

### ISSUE THREAD

**Issue by alknemeyer** [eclipse-cyclonedds/cyclonedds-python#119]
Hey. When installing from source as part the instructions in the README on current master branch, I got the following error:

```
In file included from clayer/pysertype.c:31:
clayer/pysertype.h:17:10: fatal error: Python.h: No such file or directory
    17 | #include <Python.h>
       |          ^~~~~~~~~~
compilation terminated.
error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
```

After running `sudo apt install python3-dev` it succeeds. I think the docs just need a line like: "You'll need the Python development headers to complete the install. If using `apt`, try `sudo apt install python3-dev`. For other distributions, see [this comment](https://stackoverflow.com/a/21530768)."

Otherwise I'm really excited for the upcoming v0.10.0 release -- thanks! I tested it now, and it works really well.

**Comment by thijsmie** [comment]
Hi @alknemeyer!

I agree, indeed the docs/readme should mention this explicitly! It does sound like an excellent first PR to the project, would you be willing to give it a go? 😇 If not, no worries, I'll include it in my next set of changes.

**Comment by alknemeyer** [comment]
Sure, will do!

There's another potentially missing doc (though I'm still trying to understand the error). Running `cyclonedds typeof <topic>` results in an XTypes error as follows:

![image](https://user-images.githubusercontent.com/19974131/181268976-61a92ca0-046c-4e9e-9730-1f087886df3f.png)

I enabled topic and type discovery when compiling the publishers/subscribers, and enabled topic discovery endpoints in my config file:

```xml
<Discovery>
    <EnableTopicDiscoveryEndpoints>true</EnableTopicDiscoveryEndpoints>
</Discovery>
```

The publishers/subscribers are running using CycloneDDS v0.9.1, so the issue could just be a simple version mismatch. Should I expect it to work?

**Comment by thijsmie** [comment]
Hmm, interesting. I do expect it to work, especially since you did get the `TypeIdentifier` so clearly your endpoints have XTypes information available (otherwise you would just get no results). However, they failed to provide said information within the timeout period. I just checked, the default timeout is just 2 seconds, which I assumed to be plenty, but maybe there is a lot of chatter going on? You can manually extend the timeout by editing `cyclonedds-python\cyclonedds\tools\cli\discovery\main.py:282` and I'll add an option to extend it to the CLI later.

**Comment by alknemeyer** [comment]
Python header docs added in #120
