### ISSUE TITLE
Tool to find data version mismatches + topics without publishers/subscribers

### ISSUE THREAD

**Issue by alknemeyer** [eclipse-cyclonedds/cyclonedds-python#122]
Hello. I'm looking to find/create a tool which can help my employer figure out version mismatches between the DDS nodes in our deployed system. We want a bit of software that,

1. alerts when two nodes use different (incompatible) versions of the same struct. For example, a publisher using a newer version than one of the subscribers. (Ideally, it would do something similar to `cyclonedds typeof` and display a diff of the two versions.)
2. alerts when a topic exists without a publisher or subscriber

Basically, something to help with continuous deployment/maintenance. I'd like for it to be usable both as a CLI that a human views and interacts with, and as a trigger that could ultimately result in a notification being sent for someone to investigate.

As far as I can tell, the existing tools almost perform these tasks, but using eg `cyclonedds ls` when there are 50+ topics becomes difficult. There's also info there about QoS etc that aren't relevant to this particular use case, and the tools don't differentiate between subscribers and publishers.

Assuming this tool doesn't already exist, would you be open to advising me as I create it? I would like for it to be useful for others too.

**Comment by thijsmie** [comment]
Hi @alknemeyer,

Thank you for your question! Unwittingly you have forced me to walk the thin line between being a committer of CycloneDDS in Eclipse Foundation context while also being employed at ZettaScale Technology which has some commercial offerings in the DDS space. To avoid any confusion: I am putting on my hat as a ZettaScale Technology employee and not necessarily the Open Source maintainer.

We at ZettaScale are indeed working on such a tool that encompasses a lot of fault detection on networks, like datatype mismatches, QoS mismatches and some other common pitfalls. We expect it to be finished some time this year and we will include it in our commercial offerings for CycloneDDS. There is always a balance to be struck: we love working on Open Source but the reality is that it doesn't pay our salaries, so we have to choose what extra things we can do outside of the Open Source version without compromising the functionality of it.

All that said, it sounds like you have some cool ideas and would be glad to merge any contributions of new or improved tools, even if that "hurts" the commercial offerings of my employer. The point of the project is to be fully open and it would be a stain on my honour if I did otherwise. :smile:

**Comment by alknemeyer** [comment]
Fair enough! I understand the conflict there, and needing to pay the bills. I appreciate that you're willing to merge contributions regardless. I'll close this issue but may submit something soon. Otherwise, we may pay for those tools when they become available :sweat_smile:
