### ISSUE TITLE
”libcycloneddsidlc.so.0.11.0": No   such file or directory.

### ISSUE THREAD

**Issue by ll52pp** [eclipse-cyclonedds/cyclonedds-python#228]
Hi Mrs./Mr.，
       One compile fault was found when i build cycloneDDS master branch code, my machine version is **Linux catl-A 5.4.0-150-generic #167~18.04.1-Ubuntu SMP Wed May 24 00:51:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux**,and compile steps follow cycloneDDs description, but also **libcycloneddsidlc.so.0.11.0**  not found like following screenshot:

root@catl-A:/home/catl_root/lli/cyclonedds/build#  cmake --build . --target install
[  3%] Built target idlpp
[  3%] Built target _confgen
[ 64%] Built target ddsc
[ 73%] Built target idl
[ 74%] Built target idlc
[ 76%] Built target libidlc
[ 76%] Built target ddsperf_types_generate
[ 79%] Built target ddsperf
[ 93%] Built target ddsrt-internal
[ 95%] Built target dds_security_ac
[ 96%] Built target dds_security_auth
[ 99%] Built target dds_security_crypto
[100%] Built target symbol_export_test
Install the project...
-- Install configuration: "RelWithDebInfo"
-- Installing: /home/catl_root/lli/cyclonedds/build/lib/cmake/CycloneDDS/CycloneDDSConfig.cmake
-- Installing: /home/catl_root/lli/cyclonedds/build/lib/cmake/CycloneDDS/CycloneDDSConfigVersion.cma              ke
-- Installing: /home/catl_root/lli/cyclonedds/build/lib/cmake/CycloneDDS/CycloneDDSTargets.cmake
-- Installing: /home/catl_root/lli/cyclonedds/build/lib/cmake/CycloneDDS/CycloneDDSTargets-relwithde              binfo.cmake
-- Installing: /home/catl_root/lli/cyclonedds/build/lib/pkgconfig/CycloneDDS.pc
CMake Error at src/tools/idlc/cmake_install.cmake:57 (file):
  file INSTALL cannot find
  "/home/catl_root/lli/cyclonedds/build/lib/libcycloneddsidlc.so.0.11.0": No
  such file or directory.
Call Stack (most recent call first):
  src/tools/cmake_install.cmake:57 (include)
  src/cmake_install.cmake:47 (include)
  cmake_install.cmake:86 (include)

Makefile:119: recipe for target 'install' failed
make: *** [install] Error 1

pls someone give me big help.

**Comment by eboasson** [comment]
That's weird, it just built it! (`[ 76%] Built target libidlc`)

The only thing that I wonder if it is because it seems to be installing into the build directory: the build directory is `catl-A:/home/catl_root/lli/cyclonedds/build` and it says `Installing: /home/catl_root/lli/cyclonedds/build/lib/...`. It could be that `cmake`'s installation procedure first deletes the target file and then copies the source to the target.

I don't think that is really supported by CMake, and I don't think I have ever tried that. What happens if you specify a different installation directory with `-DCMAKE_INSTALL_PREFIX=...` when configuring? (I typically install to `<build dir>/install` for doing development, that works fine.)

**Comment by ll52pp** [comment]
@eboasson  big tks for urs' reply, I changed the directory of  build tagrt,and this problem solved.
