### ISSUE TITLE
Issues with scikit-build

### ISSUE THREAD

**Issue by pbleyer** [eclipse-cyclonedds/cyclonedds-python#35]
Hi again and thanks for your previous support.

I see now that the latest branches are using scikit-build as a compile dependency. Is this change temporary or intended to be the default way to build and deploy the extension for future releases?

While I understand the rationale to use the improvements of skbuild for certain type of projects, the added complexity and relative immaturity of the tool may present issues in constrained and cross-compilation environments. In particular I spent a good chunk of the last two days adapting and troubleshooting the extension to compile and work nicely out of the box in a Yocto setup. With the previous version that didn't use skbuild, integrating the extension initially in Yocto took me minutes with a simple script and automatic builds worked flawlessly without touching the build rules again. Based on my experience I am positive I will now need to tweak the rules frequently with new skbuild or Yocto releases. 

Is using scikit-build really necessary?

Regards.

**Comment by k0ekk0ek** [comment]
Hi @pbleyer! scikit-build will be the default way to build cyclonedds-python from now on. The reason behind this is that we depend on cyclonedds, which can be compiled with various features enabled/disabled and have one or more external dependencies. The older build system could not easily determine what is there and what isn't. With scikit-build, we can depend on the exported cyclonedds targets in CMake, which automates a great deal of logic. The downside is (like you stated) that the build rules are more complicated now. Of course, the old build system did not check a number of things and therefore would've gotten more complicated either way. Another benefit of scikit-build is that it's now a lot easier to compile with Visual Studio and enable more warnings etc.

There's a good chance you'll have to tweak the build rules less frequently because a lot is determined automatically, but given that cyclonedds-python is still a young project it's hard to give any kind of guarantee.

If you're cross-compiling, I think you can use a CMake toolchain file and simplify things even further, but I haven't done any Yocto builds myself, so no guarantees there.

Hope that clarifies why we've chosen to go with scikit-build.

**Comment by thijsmie** [comment]
I did want to add that I do share some of your frustrations with scikit-build @pbleyer, for example how it handles `--use-feature=in-tree-build` (which will soon be the pip default) and how it handles switching between `Debug` and `Release` builds. I started adding some tweaks to scikit-build itself to remedy these things which I should get ready for a pull request.

If you are working around things with your build scripts or have suggestions for improvements please let me know, in the end one of the goals of this python project is to make it as easy as possible to install and use, so if you are having to fiddle around a lot to get it to work we still have work to do.

**Comment by pbleyer** [comment]
Thanks for the clarifications. Certainly makes sense if you want to sync with the CycloneDDS configuration the Python module is using, albeit the C dependencies is just the small "clayer" interface from what I can tell.

Do you envision the module to always be a separate repo from CycloneDDS or eventually it will be integrated under the main project? Some libraries that have other language extensions just enable them as a switch option during configuration time. This doesn't gain much with the dependencies and can add some complexity, but at least it makes sure the module is linked against the correct library. For example in my current project I am also using the Linux gpiod kernel module/library and I can just add the Python extensions through a configure script argument. Of course there is also the possibility to make the main repo become aware of a language extension module if it is present in some subdirectory or submodule, thus allowing the repos to be developed separately.

Yocto in particular has its own intricacies. There are host tool dependencies, native (host) compiled project dependencies, shared target project components and individual target modules. Some of these have also SDK variants and there are ways to amalgamate host/native and target configurations. The problem with scikit-build is that it is a host tool that extends distutils and I couldn't find a proper way to make Yocto aware of that without having to resort to rewriting the distutils script class that handles that type of modules, which for obvious reasons I really wanted to avoid. The most simple way I came up with is, since skbuild is just platform-independent Python scripts, build it as native module allowing cyclonedds Python extension to include it, and then redirecting the cmake layer to use the cyclonedds toolchain target configuration (non-native) that will use the target environment for cross-compilation. So it looks like a native component but with a target output. A bit messy for my taste, but it will recreate correctly the steps to build the extension.

BTW, I also had to tweak the Python pubsub tool renaming it, since it was clashing with the main pubsub binary and Yocto was justifiably confused that the modules were overwriting each other files.

**Comment by k0ekk0ek** [comment]
I think cyclonedds-python will always be kept in a separate repository. A hard-split between the repositories has the advantage it's technically clear for every extension where that split lies and avoids quick hacks across extension boundaries. There's a bunch of other project management reasons why we keep it that way. You're right in that building from source as a whole becomes somewhat simpler, but the interfaces Python must be kept compatible for other reasons too. We might have a parent repository at some point so we can pin specific versions for a release. Alternatively, we could include the core as a Git submodule in cyclonedds-python. Time will tell what mechanism works best.

If you want I can have a quick look at your project(?) I might spot an alternate solution. I don't have experience in the process for Yocto, but did setup a fair amount of embedded builds for other embedded platforms. At the very least, I'd get a feel for the problem an try taking it into account in future additions. Also, since Yocto seems to be used in a lot of places, we could introduce a CI pipeline to ensure all the basics work.
