### ISSUE TITLE
Compatibility problem between CycloneDDS-CXX publisher and CycloneDDS-Python receiver

### ISSUE THREAD

**Issue by EttoreVidotto** [eclipse-cyclonedds/cyclonedds-python#41]
Hello everyone,
I would like to report a problem discovered when trying to use a sender created with CycloneDDS-CXX and a receiver created using the corresponding Python project.
First, I created (using the code from the HelloWorld example) a publisher for the message
```idl
struct Float64
{
  double data;
};
```
The code I used for the C++ publisher is the following:
```cpp
#include <cstdlib>
#include <iostream>
#include <chrono>
#include <thread>

#include "dds/dds.hpp"
#include "Float64.hpp"

using namespace org::eclipse::cyclonedds;

int main() {
    std::cout << "=== [Publisher] Create writer." << std::endl;
    dds::domain::DomainParticipant participant(0);
    dds::topic::Topic<Float64> topic(participant, "Float64");
    dds::pub::Publisher publisher(participant);
    dds::pub::DataWriter<Float64> writer(publisher, topic);

    std::cout << "=== [Publisher] Waiting for subscriber." << std::endl;
    while (writer.publication_matched_status().current_count() == 0) {
        std::this_thread::sleep_for(std::chrono::milliseconds(20));
    }

    Float64 msg(14335.980398);
    std::cout << "=== [Publisher] Write sample." << std::endl;
    writer.write(msg);
    std::cout << "=== [Publisher] Waiting for sample to be accepted." << std::endl;
    while (writer.publication_matched_status().current_count() > 0) {
        std::this_thread::sleep_for(std::chrono::milliseconds(50));
    }
    std::cout << "=== [Publisher] Done." << std::endl;
    return 0;
}
```
Then, on the Python branch, I created the example receiver:
```py
from dataclasses import dataclass

from cyclonedds.domain import DomainParticipant
from cyclonedds.sub import Subscriber, DataReader
from cyclonedds.topic import Topic
from cyclonedds.util import duration
from cyclonedds.idl import IdlStruct

import cyclonedds.idl.types as types

@dataclass
class myfloat64(IdlStruct):
    value: types.float64

domain_participant = DomainParticipant(0)
topic = Topic(domain_participant, 'Float64', myfloat64)
subscriber = Subscriber(domain_participant)
reader = DataReader(domain_participant, topic)

for sample in reader.take_iter(timeout=duration(seconds=10)):
    print(sample.value)
```
Running both applications will cause a crash in the publisher one. Attaching a debugger to the publisher application will report the nullptr-exception as depicted in the figure:

![nullptr exception](https://user-images.githubusercontent.com/79527119/141100558-15955f49-e183-4985-95e7-a8625a6de8a9.PNG)

Adding the option `<AllowMulticast>false</AllowMulticast>` to the xml-configuration file for CycloneDDS will avoid to trigger the exception, but no message will be exchanged neither between the two different applications (the C++ publisher and Python receiver) nor the two same applications (C++ publisher and receiver or both the Python publisher and receiver). Leaving the default option, will ensure that the correct message is exchanged between publisher and receiver both written in C++ or both in Python.
Any idea/suggestion where the problem might be?

For each project I used the following master branches:
* cyclonedds: master branch, eclipse-cyclonedds/cyclonedds@26e04e6838fd6ec38a7d41fa563eb6b81cd308fb
* cyclonedds-cxx: master branch, eclipse-cyclonedds/cyclonedds-cxx@d9234aaf1c00492f37cb06db412f5f68040f8e44
* cyclonedds-python: 1e1af632cf04403b7f372a55a74b2b76da1ba996

Thank you in advance, any answer would be appreciated.
Best regards,
Ettore Vidotto

**Comment by thijsmie** [comment]
Hi Ettore Vidotto,

Thanks for your report! It seems you have two unrelated problems here, I'll go into them separately:
1) You have run into a bug in the new XTypes type lookup functionality. This is an area of active development that @dennis-adlink might be able to tell you more about. We should definitely fix this.
2) Communication between DDS endpoints does not only require a match in topic_name, but also in type_name when we are not talking xtypes. Since you did not specify a typename in the python type the name of the class will be used, so that will be `myfloat64` instead of `Float64`. You can pass a parameter to the python class to specify the typename like so:

```python
@dataclass
class myfloat64(IdlStruct, typename="Float64"):
    value: types.float64
```

Given these two things, does your demo now work? If not, could you try to use the `ddsls` tool included in the Python binding and look at the Publication and Subscription to see if there are any mismatches?

**Comment by EttoreVidotto** [comment]
Dear @thijsmie 
thank you very much for the quick answer, much appreciated.
Yes, setting the typename to `Float64` solved the problelm, great!

Regarding the idl compiler, I wanted to keep the structure as simple as possible, since it seems I cannot manage to compile the idl file. Independently of the structure not wrapped by a module, if I run the command:
```bash
idlc -l py Float64.idl
```
as you suggested, I get the error:
```bash
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
idlc: cannot load generator py
```
Running instead 
```bash
idlc -l python Float64.idl
```
gives me the error:
```bash
Cannot load generator cycloneddsidlpython.dll: The specified module could not be found.
```
I cannot find the specified dll anywhere in the system. Any idea where the problem could be now?
Thank you again for your help.
Bests,
Ettore

**Comment by AntonioCohimbra** [comment]
Dear @EttoreVidotto  and @thijsmie,

in fact I tried the same thing and discovered several issues here (all on Windows 10):

1.) The IDL Python package installation fails if the installation of cyclonedds wasn't build based on the master branch of cyclonedds. Especially the (matching) version 0.8.0, as which the Python module identifies itself, isn't compatible. No big thing but maybe worth a note in the docs.

2.) The IDL Python package installs files in the wrong place if a user installation is performed. It creates folders in C:\Users\<user>\AppData\Roaming\Python, but looks for the idlpy.dll in C:\Users\<user>\AppData\Roaming\Python\Python38\site-packages\cyclonedds\.libs, which doesn't exist. Manually copying the dll file there solves that issue (that @EttoreVidotto has), but...

3.) In this state the command `idlc -l py vehicle.idl`, executed in the examples/vehicle folder, creates the folder structure and the py file, but it is empty. Here I'm lost, since there is no error.

Any answer would be appreciated,
Best regards,
Tobias

**Comment by thijsmie** [comment]
Hi Antonio,

Thanks for your careful report. 
1.) Yes, I will change the version number to 0.9.0 to follow the cyclonedds master. 47908b595f32f49bb68a03343f05098700886e0c will be the last compatible 0.8.0 commit. Once we are in 'released' mode we will have to be more careful with the compatibility.

2.) Ah, this is scikit-build getting confused with paths on windows. I will see if I can work around this.

3.) Must be a windows specific bug... I will see if I can replicate and solve this.

**Comment by AntonioCohimbra** [comment]
Hi @thijsmie,
thanks for having a look! Meanwhile I installed everything in parallel in WSL (ubuntu) and can generate the Python types there. So I can continue for now...

**Comment by thijsmie** [comment]
```c
hours_wasted_by_debugging_absolute_windows_crap += 10;
```

So yeah, I have spent a decent amount of time pulling my hair out over what could possibly be wrong. By using `procdump` and `windbg` I figured out there was a heap corruption, but I did not see how that could happen. On linux it runs fine, valgrind and address_sanitizer included. Even tools like `DrMemory` and the Microsoft Address Sanitizer just told me stuff like: "this pointer is not valid". My reproducer got smaller and smaller full of print statements until it finally clicked: **memory `malloc'ed` in `cycloneddsidl.dll` cannot be `free'd` in `idlpy.dll`** which led me to [this article](https://docs.microsoft.com/en-us/cpp/c-runtime-library/potential-errors-passing-crt-objects-across-dll-boundaries?view=msvc-170).

I have confirmed that copying all `idl_` functions that deal with strings and files over to `idlpy` indeed fixes the problem, altough that is not particularly elegant of course. I'll discuss with @eboasson and/or @k0ekk0ek what the best approach is.

**Comment by slietzau** [comment]
If `cycloneddsidl.dll` and `idlpy.dll` both use the *dynamic* windows CRT (`/MD`), it *should* work. Maybe it's worth a try to force `/MD` on windows?

**Comment by thijsmie** [comment]
Hi @slietzau, it does indeed work that way, however it doesn't really mesh with the rest of the cyclonedds design philosophy (where we have dds_alloc/dds_free). We will do some restructering on the cycloneddsidl side so we can fix this issue in a satisfactory way. For now, if anyone is working with idlc on windows you can either add the `/MD` flag in idl/idlc/idlpy cmake configurations or use [this commit](https://github.com/thijsmie/cyclonedds-python/commit/8daa843b059ccc003770f437455c27b100d6ffa2) which copies over some functions to avoid passing pointers between libraries, which is of course non-elegant but works.
