### ISSUE TITLE
repeated module groups only generate the last one

### ISSUE THREAD

**Issue by ghorn** [eclipse-cyclonedds/cyclonedds-python#78]
This IDL has two structs in the same `module ModA`, but they are declared in two separate module groups:
```
module ModA {
    struct FooA {
        long x;
    };
};

module ModA {
    struct FooB {
        long y;
    };
};
```
The invocation `idlc -l path/to/idlpy.so yolo.idl` generates this code:
```
"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.9.0
  Module: ModA
  IDL file: yolo.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import ModA


@dataclass
@annotate.final
@annotate.autoid("sequential")
class FooB(idl.IdlStruct, typename="ModA.FooB"):
    y: types.int32
```

As you can see, only the second struct shows up. If I change the IDL to this
```
module ModA {
    struct FooA {
        long x;
    };

    struct FooB {
        long y;
    };
};
```
to group the structs in one module group, it generates the proper code
```
# blah blah blah

@dataclass
@annotate.final
@annotate.autoid("sequential")
class FooA(idl.IdlStruct, typename="ModA.FooA"):
    x: types.int32


@dataclass
@annotate.final
@annotate.autoid("sequential")
class FooB(idl.IdlStruct, typename="ModA.FooB"):
    y: types.int32
```

The C and C++ generators accept either IDL, so I think it's an issue with the python generator.

**Comment by thijsmie** [comment]
Hi @ghorn,

Thanks for reporting this issue. I have confirmed that this goes wrong in the Python IDL generator. It is not immediately clear to me how to solve this since I somehow have to trace if modules were already opened in the current run to not overwrite already generated output. That comes with a heap of headaches because of tracing imports for headers. I'll discuss with @dpotman if we can actually fix this 'upstream' by combining all calls to the same module to a single tree walk. That avoids this issue in Python entirely _and_ prevents it in any future language binding.

**Comment by ghorn** [comment]
When I ran into this, I read the python generator code and came to the conclusion that it was an issue with the core `idlc` logic, not the python generator, which is what I think you are saying.

That was confusing to me because when I call the C++ generator on the same IDL file, it correctly emits every struct and not only the last struct. Does this make any sense to you?

**Comment by thijsmie** [comment]
Hey @ghorn!

So the problem here is simply that for python the problem of reopening modules is handled nowhere, while the C++ generator implements a solution for it by itself. This is because idlc is, in my opinion, a little bit _too_ generalized to the IDL grammar. You'll also note that between the C, C++ and Python generator there is already quite some duplication and handling of the same problems.

By the way, if you are in need of a solution for this right now, you could split your idl file into two and perform two separate idlc runs, this will result in correct python output.

**Comment by ghorn** [comment]
Ah thanks, that makes sense. My workaround was to process the IDL file and merge groups before calling idlc.
