### ISSUE TITLE
Installing on Chromebook via pip3 fails: No module named cyclone_search

### ISSUE THREAD

**Issue by pscheie** [eclipse-cyclonedds/cyclonedds-python#89]
I'm trying to install cyclonedds-python on my Chromebook using pip (pip3).  It's failing saying it can't find the module cyclonedds_search:
```
pscheie@penguin:~$ sudo pip3 install cyclonedds
Collecting cyclonedds
  Downloading https://files.pythonhosted.org/packages/d2/58/09e4457a6ee674cd3556731ed57e422355b47c47dcde600d5b40af37c693/cyclonedds-0.9.1.tar.gz (94kB)
    100% |████████████████████████████████| 102kB 1.0MB/s 
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-37yc2uud/cyclonedds/setup.py", line 23, in <module>
        from cyclone_search import find_cyclonedds
    ModuleNotFoundError: No module named 'cyclone_search'
        ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-37yc2uud/cyclonedds/
```
One additional data point: Prior to trying to install cyclonedds-python, I was able to successfully install cyclonedds from source on the Chromebook.  After the above failure, I tried installing cyclonedds-python from source and got the same error about not finding cyclone_search. 

Suggestions?

**Comment by thijsmie** [comment]
Well this is a weird one, I hadn't expected the chromebook version to be any different than the normal linux versions. Anyway, it is clear that the `pip install cyclonedds` already yields you a build-from-source version because no appropriate `wheel` is available. I don't know if we can build the right wheels in CI for you, I'll put that on the "to investigate" list.

Can you try to update your pip3? It might be just that it doesn't quite work with older pip versions. I also made [a branch](https://github.com/thijsmie/cyclonedds-python/tree/buildhelp-via-importlib) for you using a slightly different mechanism to get 'cyclone_search' imported. Can you give that a go?

Lastly, I see you are directly installing the cyclonedds package into your system python. For several reasons, that is not the best idea. I recommend you look into tools like `virtualenv` or `poetry` to manage virtual environments to install your packages in.

**Comment by pscheie** [comment]
Hi @thijsmie,
I updated pip3 from version 18.1-5 (that comes in the Debian Linux 10.6 "container" that Chromebook provides) to 22.1.1, and then I was able to successfully install cyclonedds-python using pip3.  Thanks for the advice.  Did you still want me to try installing from that other branch?

Yes, you're correct, I should use virtualenv (never tried poetry; suppose I should), and I have experimented with it in the past.  But then I put things aside for a while, and when I come back I find I've forgotten everything WRT using virtualenv.  That's not a reason, it's just my flimsy excuse.  I was on holiday and when I saw the updates you all had made with Cyclonedds, I wanted to take it out for a spin right away.  But the only computing device I had with me was the Chromebook, so I thought I'd give it a try.  Once I updated pip, it worked.  But I agree I should make use of virtualenv.  I should also eat more vegetables and exercise more, but one thing at a time.  I'll delve into virtualenv (and checkout poetry) because that's more interesting than veggies or exercise. ;-)

Thanks for the help.

**Comment by thijsmie** [comment]
Hi @pscheie,

Good to hear a simple pip update helped, I'll do some research on what versions are actually compatible and add a note somewhere. No need to try the other branch, that change solves another potential issue that is clearly not what you encountered.

Cool to hear that you can experiment with Cyclone on the go with a Chromebook! However, I have to disagree with you on your last point, vegetables are definitely more interesting than a python packaging tool 😜.
